# Generated by Django 4.2.13 on 2024-05-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SurfaceDamage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight", models.CharField(max_length=1024)),
                ("damage_type", models.CharField(max_length=1024)),
                ("level", models.CharField(max_length=1024)),
                ("part", models.CharField(max_length=1024)),
            ],
        ),
    ]
