# Generated by Django 4.2.13 on 2024-05-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surface", "0002_remove_surfacedamage_flight_flightdamage"),
    ]

    operations = [
        migrations.AddField(
            model_name="surfacedamage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="surface_damage/main/"
            ),
        ),
        migrations.AddField(
            model_name="surfacedamage",
            name="metadata",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
