# Generated by Django 4.2.13 on 2024-05-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surface", "0003_surfacedamage_image_surfacedamage_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surfacedamage",
            name="part",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
