# Generated by Django 4.2.13 on 2024-05-25 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0001_initial"),
        ("surface", "0004_alter_surfacedamage_part"),
    ]

    operations = [
        migrations.AddField(
            model_name="surfacedamage",
            name="flight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="flight.flight",
            ),
        ),
        migrations.DeleteModel(
            name="FlightDamage",
        ),
    ]
