# Generated by Django 4.2.13 on 2024-05-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WireFault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fault_detected", models.BooleanField()),
                ("component_name", models.CharField(max_length=255)),
                ("fault", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("raw", models.TextField()),
            ],
        ),
    ]
