# Generated by Django 4.2.13 on 2024-05-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wire", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wirefault",
            name="component_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="wirefault",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="wirefault",
            name="fault",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="wirefault",
            name="fault_detected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="wirefault",
            name="raw",
            field=models.TextField(null=True),
        ),
    ]
