# Generated by Django 4.2.13 on 2024-05-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_data", models.TextField()),
                (
                    "file",
                    models.FileField(
                        blank=True, default=None, null=True, upload_to="ingest/uploads/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("failed", "Active"),
                            ("processing", "Processing"),
                            ("complete", "Complete"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
            ],
        ),
    ]
