# Generated by Django 4.2.13 on 2024-05-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("failed", "Failed"),
                    ("processing", "Processing"),
                    ("complete", "Complete"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
