# Generated by Django 4.2.13 on 2024-05-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conversation_id", models.CharField(max_length=1024)),
                ("user_id", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("usr", "user"), ("mod", "model")],
                        default="mod",
                        max_length=64,
                    ),
                ),
                ("message", models.CharField(max_length=4096)),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
