# Generated by Django 4.2.13 on 2024-05-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversationhistory",
            old_name="user_id",
            new_name="chat_id",
        ),
        migrations.RemoveField(
            model_name="conversationhistory",
            name="conversation_id",
        ),
        migrations.AddField(
            model_name="conversationhistory",
            name="message_id",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="conversationhistory",
            name="metadata",
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="conversationhistory",
            name="username",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
