# Generated by Django 4.2.13 on 2024-05-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_rename_user_id_conversationhistory_chat_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationhistory",
            name="metadata",
            field=models.JSONField(default=None),
        ),
    ]
