# Generated by Django 4.2.13 on 2024-05-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_alter_conversationhistory_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationhistory",
            name="metadata",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
