# Generated by Django 4.2.13 on 2024-05-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0004_alter_conversationhistory_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_token", models.CharField(max_length=4096)),
                ("bot_type", models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name="conversationhistory",
            name="message",
        ),
        migrations.RemoveField(
            model_name="conversationhistory",
            name="message_id",
        ),
        migrations.RemoveField(
            model_name="conversationhistory",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="conversationhistory",
            name="role",
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("username", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("usr", "user"), ("mod", "model")],
                        default="mod",
                        max_length=64,
                    ),
                ),
                ("message", models.CharField(max_length=4096)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=None, null=True)),
                (
                    "conversation_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.conversationhistory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConversationProcessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_data", models.JSONField(blank=True, default=None, null=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pend", "pending"),
                            ("comp", "completed"),
                            ("fail", "failed"),
                        ],
                        default="pend",
                        max_length=8,
                    ),
                ),
                (
                    "conversation_history",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.conversationhistory",
                    ),
                ),
            ],
        ),
    ]
