# Generated by Django 4.2.13 on 2024-05-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0005_bot_remove_conversationhistory_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="bot_name",
            field=models.CharField(
                blank=True, default=None, max_length=4096, null=True
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="bot_url",
            field=models.CharField(
                blank=True, default=None, max_length=4096, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="bot_type",
            field=models.CharField(
                choices=[("TELE", "Telegram")], default="TELE", max_length=8
            ),
        ),
    ]
