# Generated by Django 4.2.13 on 2024-05-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0006_bot_bot_name_bot_bot_url_alter_bot_bot_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="status",
            field=models.CharField(
                choices=[
                    ("ini", "Initializing"),
                    ("RUN", "Running"),
                    ("PAU", "Paused"),
                    ("FAI", "Failed"),
                ],
                default="ini",
                max_length=8,
            ),
        ),
    ]
