# Generated by Django 4.2.13 on 2024-05-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0008_bot_bot_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
