# Generated by Django 4.2.13 on 2024-05-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0010_bot_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="status",
            field=models.CharField(
                choices=[
                    ("inactive", "In Active"),
                    ("active", "Active"),
                    ("failed", "Failed"),
                ],
                default="inactive",
                max_length=8,
            ),
        ),
    ]
