# Generated by Django 4.2.13 on 2024-05-19 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0011_alter_bot_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationhistory",
            name="bot",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bot.bot",
            ),
        ),
    ]
